services:
  anaconda:
    build: 
      context: .
      dockerfile: Anaconda.Dockerfile
    ports:
      - 8888:8888 # Jupyter notebook
    volumes:
      - ./sampledata:/home/anaconda/notebooks

