services:
  hadoop:
    build: 
      context: .
      dockerfile: Hadoop.Dockerfile
    hostname: hadoop-server
    ports:
      - 8088:8088 # Hadoop main
      - 9870:9870 # Hadoop browser
    volumes:
      - ./sampledata:/home/hadoop/sampledata
      - hadoop_store:/home/hadoop/hadoop_store

volumes:
  hadoop_store: {}
