services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hue
      MYSQL_USER: hue
      MYSQL_PASSWORD: secretpassword
    volumes:
      - mysql_data:/var/lib/mysql

  hue:
    image: gethue/hue:latest
    ports:
      - 8000:8888 # Hue
    volumes:
      - ./setup-on-ubuntu-scripts/hue-config/hue.ini:/usr/share/hue/desktop/conf/hue.ini
      - ./sampledata:/sampledata
    depends_on:
      - mysql

volumes:
  mysql_data: {}
