services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hue
      MYSQL_USER: hue
      MYSQL_PASSWORD: secretpassword
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  hue:
    image: gethue/hue:latest
    ports:
      - 8000:8888 # Hue
    volumes:
      - ./setup-on-ubuntu-scripts/hue-config/hue.ini:/usr/share/hue/desktop/conf/hue.ini
      - ./sampledata:/sampledata
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data: {}
